npmgraph/npmgraph

- index.css
- index.html
- js/Graph.js
- js/ModulePane.js
- js/Store.js
> Show deprecated modules and warnings

- js/Inspector.js
Reusing the same tab is unusual and unexpected. I'd suggest always opening a new tab like most other websites do.
> Open links in a new tab

- .github/workflows/ci.yml
This will ensure that linting passes before merging any PRs
> Enable CI on repo

- README.md
- js/Inspector.js
- package.json
- https://github.com/npmgraph/npmgraph
- https://npmgraph.js.org
Awaiting https://github.com/js-org/js.org/pull/5788
> chore: update URLs

- js/InfoPane.js
Replaces and closes #17. Reimplemented with the minimum amount of changes
> Add file picker for package.json

- js/App.js
- js/InfoPane.js
- js/Inspector.js
> fix: empty query clears url params

- js/Graph.js
I looked into using a dynamic `import()` call, but wasn't able to get that to work. I don't think Parcel is set up for `url:` style dynamic-imports.  This issue is alluded to in https://github.com/parcel-bundler/parcel/issues/4498, but 'not entirely sure that issue covers our use case.
Regardless, I'm not sure it actually matters all that much because the static import isn't actually fetching the file. All it does is yield a URL to the file (which Parcel has copied into the `dist` directory).  The `fetch()` to get the file happens in our code [here](https://github.com/npmgraph/npmgraph/blob/main/js/Graph.js#L11-L16), once the graph module is loaded.  But it's async and doesn't block the initial page load / render.
So, I don't think we can do much to optimize how/when the WASM file is …
> fix: improved graph rendering logic, fixes #64

- js/bugsnag.js
Fixes #69 
If an error happens, the error page already mentions opening an error
https://github.com/npmgraph/npmgraph/blob/a9e59ea526a1dd2522a949021f7b51cc1aea89ae/index.html#L85
> Hide bugsnap error

- js/Store.js
https://github.com/npm/node-semver#usage
> Treeshake semver dependency

- css/Graph.scss
- js/Graph.tsx
Center-aligns graphs in 1:1 mode.  Fixes #110.
> fix: center small graphs

- js/components/App.tsx
- js/components/Inspector.tsx
- js/graphdiagram/GraphDiagram.tsx
- js/graphdiagram/GraphDiagramZoomButtons.tsx
- js/graphpane/GraphPane.tsx
- js/util/guards.ts
- js/util/sharedStateHook.ts
- js/util/useGraphSelection.ts
- js/util/useHashParam.ts
- js/util/useSearchParam.ts
The problem was the `useQuery` react hook wasn't properly updating the location when set.  The fix was to use `useLocation` to manage the underlying query state rather that `shareStateHook`.
> fix: fix #152

- components/InfoPane/QueryInput.scss
- components/Inspector.scss
I might add here some style improvements
> Style fixes 

- components/App/App.scss
- components/App/App.tsx
- components/App/Loader.scss
- components/GraphDiagram/GraphDiagram.scss
- components/Inspector.tsx
- components/Splitter.tsx
- index.scss
Placing it there was not necessary. I think that keeping it stable in the corner makes more sense
> Move splitter to the right

- README.md
This is wrong, how do you generate this URL?
> Add URL parameter demo code

- README.md
- Fixes https://github.com/npmgraph/npmgraph/issues/218
For reference, this was used in https://github.com/npmhub/npmhub/pull/179/files
I pointed it out in my first PR but then we got sidetracked 😅 https://github.com/npmgraph/npmgraph/pull/193#discussion_r1432506922
> Improve `packages` parameter documentation

- components/Inspector.scss
See jumpy toggle (only visible when the graph is not empty, e.g. on https://npmgraph.js.org/?q=express)
https://github.com/user-attachments/assets/99b4e759-3624-4825-b974-84cc25727b3f
> Sidebar toggle animation fix

- components/AboutPane/AboutPane.tsx
- components/Inspector.scss
- components/Inspector.tsx
> Slightly rework sidebar style

- components/GraphDiagram/GraphDiagram.tsx
- Fixes https://github.com/npmgraph/npmgraph/issues/226
> Fix first-load scroll on Safari and Firefox

- components/GraphDiagram/GraphDiagram.tsx
Fixes [this issue](https://github.com/npmgraph/npmgraph/pull/229#issuecomment-2226908197)
> fix: scroll to selection on first load

- components/GraphDiagram/GraphDiagram.tsx
- components/ModulePane/ModulePane.tsx
- lib/useGraphSelection.ts
Added react state for tracking when the view should / should not scroll to the root node if no other modules are selected.
> fix: improved scrolling logic, fixes #233

- components/GraphPane/GraphPane.scss
- components/GraphPane/GraphPane.tsx
- components/GraphPane/reports/reporters/modulesAll.tsx
- Fixes https://github.com/npmgraph/npmgraph/issues/247
> fix: hide empty sections in Graph tab

- components/GraphPane/ModuleTable.tsx
- components/GraphPane/reports/ReportItem.tsx
- components/GraphPane/reports/reporters/licensesAll.tsx
- components/GraphPane/reports/reporters/licensesKeyword.tsx
- components/GraphPane/reports/reporters/licensesMissing.tsx
- components/GraphPane/reports/reporters/maintainersAll.tsx
- components/GraphPane/reports/reporters/modulesAll.tsx
- components/GraphPane/reports/reporters/modulesDeprecated.tsx
- components/GraphPane/reports/reporters/modulesRepeated.tsx
- components/GraphPane/reports/reporters/peerDependenciesAll.tsx
- components/ModulePane/ModulePane.tsx
- components/ModulePane/ModuleScoreBar.tsx
- components/ModulePane/ModuleTreeMap.tsx
- components/ModulePane/ReleaseTimeline.tsx
- components/Section.tsx
- components/Selectable.module.scss
- components/Selectable.tsx
- components/Unsupported.tsx
- lib/types.d.ts
- package-lock.json
- package.json
- tsconfig.json
- Fixes https://github.com/npmgraph/npmgraph/issues/255
> fix: build errors

- components/ModulePane/ModuleVersionInfo.tsx
- package-lock.json
1. Search an old version: `mem@8`
2. Visit the latest with one click:
> feat: linkify latest version

- components/InfoPane/QueryInput.tsx
- close https://github.com/npmgraph/npmgraph/issues/296
Demo:
1. cmd-enter
2. enter
3. cmd-enter
https://github.com/user-attachments/assets/52b605fc-93f9-4dc3-9a72-f1fbd3a497a2
> feat: support cmd+enter to search in new tab

- index.html
@broofa mind if I take a look a the stats for the website? Just curious how it's looking and if there are any warnings. You should probably also add your own verification
> chore: add metatag for Google Search Console

- components/GraphDiagram/graph_util.ts
- lib/ModuleCache.ts
Something in #316 broke graph rendering for modules like `express` and `npm`.  (Just getting blank graphs).
Reverting temporarily while I figure out the problem/solution (which I don't have time for this week.)
> fix: revert PR #316
