index.css

1. Visit http://npm.broofa.com/?q=webpack
2. Resize the window vertically
3. Notice the tabs getting squished

Avoid shrinking tabs on large dependency trees

---

js/Store.js

Namespaced package names need to be escaped, notice the `%2F`:

Escape module name in loader

---

index.html

This was not really a problem, but I found few small issues (and unnecessary code) in the HTML:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fnpmgraph.js.org%2F
This PR fixes everything except the `|` character. It could be replaced with `%7C` too but then it wouldn't be as readable.

Validate HTML

---

css/Graph.scss
css/InfoPane.scss
css/Inspector.scss
css/ModulePane.scss
css/index.scss
js/ModulePane.js
package.json

This PR brings minimal changes just to add support for dark mode without affecting other parts of the code and without changing the light mode (which only has minimal changes).
The sidebar is slightly tinted red/orange, but it could be easily just brought back to a gray. Further theme improvements could be made later, but at least now we can have a workable theme without large swaths of white.

Add dark mode

---

js/Graph.js

- Follows #91 
I'm going to leave this PR open a bit in case we see any other issues with simple fixes
https://npmgraph.js.org/?q=sntp@1.0.9
👆 this URL can probably always be used to test npmgraph since it has deprecated modules and few dev dependencies

Dark mode improvements

---

css/App.scss
css/Components.scss
css/Inspector.scss
css/index.scss
index.html
js/App.js
js/Components.js
js/Inspector.js

This should not result in any changes to the UI.  Just getting rid of the last vestiges of the theme-dark / theme-light that I had originally used for theming the UI.  The only real change required for this was to create the `--bg-tabs` var to abstract out the background color used by the tabs, splitter, and loader.
Everything else here is just cleanup that flows from the above.

fix: remove theme-lite/theme-dark abstractions

---

css/Graph.scss
js/Graph.js

Graph nodes were always rendering in "light" colors, which is annoying.  Now they follow user's system theme...
Before:
After:

fix: graph nodes use theme colors

---

css/Graph.scss
css/index.scss
js/Graph.js

* arrowheads were not filled in in dark mode (see below)
* remove background `polygon` in SVG to allow page background to show through
* remove `html` `background` CSS so the user-agent background is used
* remove the `[fill=...]` and `[stroke=...]` CSS attribute-hacks for tweaking SVG fill and stroke colors, as they no longer apply to anything.
Before:
After:

fix: minor theme color issues

---

js/Store.ts
js/util.ts

One of my more recent PRs (too lazy to track down which one) introduced a bug that caused rendering to break if one of the modules was not found in the NPM repo.  This was due to failed repo requests *not* resulting in a stub module, which led to graphs that looked like this:
This fix returns the prior (correct) behavior, and also improves error messaging shown in the module pain in the event there is an error. E.g.:
To test: Show any graph that has a non-existent module.  E.g. https://npmgraph.js.org/?q=cgm-remote-monitor

fix: broken request error handling

---

js/Inspector.tsx
js/ModulePane.tsx
js/types.ts

Fixing another error that's been showing up in Bugsnag.  Basically the issue was that React hooks were conditionally called in `ModulePane`, which would break the module pane when you clicked between a normal module vs. a stub module in the graph pane, like so...
Fix was to just move some code around.
Unrelated: Typescript was complaining about some typing issues.  Fixed those.

fix: react hook errors, npmsio types

---

index.html
js/Graph.tsx
js/Module.ts
js/ModulePane.tsx
js/Store.ts
js/index.tsx
package-lock.json
package.json

In https://github.com/npmjs-cf/meta/issues/7, @terinjokes mentions that `registry.npmjs.org` is now served with CORS headers.  Upon further investigation, it looks like it's now served through cloudflare, which is pretty much the whole point of the `.cf` mirror.  Given this, there doesn't appear to be much reason for us to continue using the `.cf` mirror. 
I also ran `npx npm-check-updates -u` to update all our dependencies.  This was "mostly painless".  (`react` and `react-dom` required a couple minor tweaks due to the change from 17 -> 18).

Switch to using registry.npmjs.org, update libs

---

README.md
index.html
js/Graph.tsx
js/GraphPane.tsx
js/InfoPane.tsx
js/Inspector.tsx
js/ModulePane.tsx
js/types.ts
package.json

Just a minor capitalization fix: `NPM` -> `npm`
npm should never be capitalized:
https://github.com/npm/cli#is-it-npm-or-npm-or-npm
Also, npms.io does not use uppercase characters:
https://npms.io/about

Use lowercase for npm

---

js/components/App.tsx
js/components/QueryLink.tsx
js/util/sharedStateHook.ts
js/util/useHashParam.ts
js/util/useLocation.ts
js/util/useSearchParam.ts

Feels like I've finally got the overall behavior of the app when navigating figured out. Rules are basically this...
* Changing the query (entry points for graph) pushes a new entry on browser history.  This also resets the `location#hash`, which is where the view configuration is stored.
* Changing the view configuration (`location.hash`) *replaces* the current history entry
The end result is that you can go back and forth between various graphs in your history and change the view configuration.  And, because none of this actually refreshes the page, the in-memory module and request caches stay intact.  And because the latest version of graphviz is really performant, it all feels really snappy now.

fix: hash and search param behavior when navigating

---

components/InfoPane/FileUploadControl.tsx
components/InfoPane/QueryInput.tsx
lib/Module.ts
lib/ModuleCache.ts
lib/constants.ts
lib/useQuery.tsx

https://npmgraph-git-unnamedpackages-npmgraph.vercel.app/
Module w/ no name or version:
https://npmgraph-git-unnamedpackages-npmgraph.vercel.app/?q=Unnamed+package#packages=%5B%7B%22dependencies%22%3A%7B%22send%22%3A%220.18.0%22%7D%2C%22name%22%3A%22Unnamed+package%22%7D%5D
Module w/ name, no version: 
https://npmgraph-git-unnamedpackages-npmgraph.vercel.app/?q=my+silly+name#packages=%5B%7B%22name%22%3A%22my+silly+name%22%2C%22dependencies%22%3A%7B%22send%22%3A%220.18.0%22%7D%7D%5D
Module w/ version, no name:
https://npmgraph-git-unnamedpackages-npmgraph.vercel.app/?q=Unnamed+package%40my+silly+version#packages=%5B%7B%22version%22%3A%22my+silly+version%22%2C%22dependencies%22%3A%7B%22send%22%3A%220.18.0%22%7D%2C%22name%22%3A%22Unnamed+package%22%7D%5D

fix: unnamed / unversioned module handling

---

.prettierrc.json
README.md
components/App.scss
components/GraphDiagram/GraphDiagram.scss
components/GraphPane/GraphPane.scss
components/InfoPane/FileUploadControl.scss
components/InfoPane/QueryInput.scss
components/Inspector.scss
components/Loader.scss
components/ModulePane/ModulePane.scss
components/Toggle.scss
index.scss
lib/flash.scss
package-lock.json
package.json

Configuring `prettier` to have a deterministic sort order for CSS properties.
I'd like these to just be plain alphabetic, but am running into https://github.com/Siilwyn/prettier-plugin-css-order/issues/35 so it's the default order ("concentric-css") for now.
(Editorial: While I'm sure "concentric-css" is well-reasoned, unless you take the time to understand that reasoning - which I'm not particularly interested in doing at the moment - it's effectively random.  So... :shrug".  Here's hoping that bug gets fixed soon.)

chore: prettier css sorting

---

components/GraphDiagram/GraphDiagram.tsx
index.html
lib/DiagramTitle.tsx
lib/index.tsx

Keeps the initial window title as the default title to use when there's no active query.  Also moves title logic into it's own root react element, because why not. :-)

fix: closes #158

---

.gitignore
art/README.md
art/icons.svg
components/ExternalLink.tsx
components/GraphDiagram/GraphDiagram.scss
components/GraphDiagram/GraphDiagram.tsx
components/GraphDiagram/GraphDiagramDownloadButton.tsx
components/GraphDiagram/GraphDiagramZoomButtons.tsx
components/Icons.tsx
components/ModulePane/ModulePane.tsx
components/Section.tsx
index.html
index.scss
lib/Module.ts

Needed a icon for a github link in my other branch, which doesn't exist in the "material" icon set.  And, also, the horz. and vert. zoom icons have bugged me for *years*... so I'm switching to an SVG-based "Icon" component of my own creation that's a bit more versatile.
This provides a not-terrible way of incorporating icons from other SVG icon suites (copy/paste the SVG into Inkscape and massage to fit), and of making custom icons.
This removes the Material font dependency (128KB)... not that it matters.   That font is almost certainly in most users' browser cache.

refactor: use custom SVG icons

---

components/GraphDiagram/GraphDiagram.scss
components/GraphDiagram/GraphDiagram.tsx
components/GraphDiagram/graph_util.ts
components/Icons.scss
lib/ModuleCache.ts

Changes selection in the graph diagram as follows:
* Selected module highlighted in orange (as before)
* All downstream dependencies highlighted in orange (not just immediate dependencies)
* All upstream dependencies highlighted in blue
* Any edges or nodes outside of the selected modules' dependency graph are dimmed (opacity=0.35)
@fregante Any feedback you have on behavior or styling would be great.   I've been wanting to implement this selection behavior for a long time, as it feels a lot more intuitive to me so I'm hoping you think it's an improvement. :-)

feat: selection shows full up/downstream dependencies (fixes #144, fixes #72)

---

components/App/App.tsx
components/GraphDiagram/GraphDiagram.tsx
components/GraphPane/GraphPane.tsx
lib/constants.ts
lib/useCollapse.ts

Renames "excludes" to "collapse" in all the places.  Also keep `collapse` state in URL hash rather than in-memory, since it's part of the view configuration.

feat: store collapse state in URL hash

---

components/GraphPane/colorizers/BusFactorColorizer.tsx
components/GraphPane/colorizers/LegendColor.tsx
components/GraphPane/colorizers/ModuleTypeColorizer.tsx
components/GraphPane/colorizers/NPMSColorizer.tsx
components/GraphPane/colorizers/OutdatedColorizer.tsx
components/GraphPane/colorizers/index.ts
index.scss
lib/Module.ts
lib/ModuleCache.ts
lib/fetchJSON.ts

Adds an "Outdated Level" colorizer that colors modules by how out of date they are.
Note: There's no UI currently for showing what the latest version is, but that seems like a pretty obvious and simple addition.  I'll open a new issue for that.

feat: colorize by "outdated" level, fix #138

---

components/GraphDiagram/graph_util.ts
components/GraphPane/colorizers/ModuleTypeColorizer.tsx
components/GraphPane/colorizers/OutdatedColorizer.tsx
lib/Module.ts
lib/ModuleCache.ts
lib/bugsnag.ts
lib/fetchJSON.ts
lib/module_util.ts
package-lock.json
package.json

'Been making requests for module manifests from the NPM registry using `Accept: application/vnd.npm.install-v1+json` since that's recommended in a couple places in NPM docs, but it turns out to be [just... dumb](https://github.com/npm/feedback/discussions/749).
Switching back to the regular `application/json` API nets us more data about modules and smaller response sizes.  It also allows us to avoid making additional requests for the ModuleTypeColorizer.

refactor: revert to "application/json" registry API

---

components/GraphPane/colorizers/NPMSColorizer.tsx
components/ModulePane/ModulePane.tsx
lib/fetchJSON.ts
lib/useCommits.ts

Adds support for  a `timeout` on fetchJSON() requests, and also makes non-essential requests (e.g. npms.io, bundlephobia, github commits list) "silent" so they don't trigger the Activity component (which tends to interfere with the tab bar.)

fix: don't let fetch() requests interfere with UI

---

components/Inspector.tsx
components/ModulePane/ModuleBundleSize.tsx
components/ModulePane/ModuleNpmsIOScores.tsx
components/ModulePane/ModulePane.tsx
components/ModulePane/ModuleVersionInfo.scss
components/ModulePane/ModuleVersionInfo.tsx
lib/Module.ts
lib/ModuleCache.ts

Adds a component in the module pane that shows how the module version compares to `latest`.
NOTE:  I disable this component when the user has "Colorize by:" active and set to something other than "Outdated Level".  I'm not 100% sure that's the right thing to do, but  the different color semantics felt a bit jarring.

feat: display module version outdated-ness, closes #175

---

components/ModulePane/ModuleNpmsIOScores.tsx
components/ModulePane/ModulePane.tsx
components/ModulePane/ReleaseTimeline.module.scss
components/ModulePane/ReleaseTimeline.tsx
lib/useMeasure.ts
package-lock.json
package.json
tsconfig.json

Adds a chart in the module pane that shows a scatter-graph-esque plot of the module release history.  For example (`express`):
'Threw this together this weekend on a bit of a whim.  Clicking around on different modules it's actually pretty interesting.  'Does a really good job at communicating the pace of change of a module over time,  and also speaks to how well-maintained a module is.

feat: module release timeline chart

---

lib/index.tsx

Previously this method would always return false regardless of whether the expected features are found or not.
Fixes a regression in https://github.com/npmgraph/npmgraph/pull/200

Fix return value for hasExpectedFeatures

---

components/App/App.tsx
components/GraphDiagram/GraphDiagram.tsx
components/InfoPane/QueryInput.tsx
components/Inspector.tsx
components/QueryLink.tsx

'Fixing an issue where clicking a shared link that has a module selection (`select` hash param) opens the inspector to the `graph` pane of the 'module' pane.
For example, [this link](https://npmgraph.js.org/?q=sshpk#select=exact%3Aecc-jsbn%400.1.2) should look like this:
... but actually looks like this:

fix: show appropriate inspector pane on page load

---

.gitattributes

By default `autocrlf` is `true` on Windows so this ensures only LF is used regardless

chore: add .gitattributes enforcing LF

---

components/App/Loader.scss

When the loader overlaps the tabs, it's impossible to do anything, you just have to wait. This is particularly a problem when the package is large: https://npmgraph.js.org/?q=web-ext
This PR just moves the bar to the bottom as a quick fix:
Combined with #224 it will look better down there.

Keeps tabs visible while loading

---

components/App/Loader.scss

Reverts npmgraph/npmgraph#227
I think it's not a good position, it's hard to notice anything is happening. I think it needs to stay on top. Either we revert this for now (and I open a tracking issue) or I move it to the top left corner instead, with rounded corners perhaps.

Revert "Keeps tabs visible while loading"

---

lib/Module.ts
lib/module_util.ts
tsconfig.json

Here's what the fixed graph from #143 looks like after this change:
This PR adds code that [rather forcefully] resolves "npm:..."-style aliases in `package#*dependencies` structures so they point to the source unaliased package.  Solution is a bit heavy-handed (I'd rather not mutate package structures) but it fixes the problem at the source, and the aliased names are only relevant when it comes to the name used to save packages in node_modules directories on disk.

fix: handle npm:-style dependency aliases, fixes #143

---

package-lock.json
package.json
tsconfig.json

I noticed that types weren't actually being verified, but were only visible in the IDE and to ESLint

Add type-checking

---

components/App/Loader.scss
components/App/Loader.tsx
index.scss

Retry of https://github.com/npmgraph/npmgraph/pull/227
- The bar is moved to the top border, like GitHub.com does for example
- The activity ticker is moved to the top left, without a background. If there's text below it, it appears as a shadow:
https://github.com/user-attachments/assets/2d24f2be-49dc-4ec0-a221-5e6f018247d3

feat: keeps tabs visible while loading

---

components/GraphDiagram/GraphDiagram.scss
components/GraphDiagram/GraphDiagram.tsx
components/GraphDiagram/graph_util.ts

Sometimes I just want to explore a module in a new tab. This enables it via the standard cmd+click.
I think `metaKey` doesn't work on Windows so if accepted I'll have to do ua-sniffing and enable it on `ctrlKey` as well.

feat: allow opening modules in a new tab

---

components/ModulePane/ModulePane.tsx
index.scss

- Closes https://github.com/npmgraph/npmgraph/issues/246

fix: hide Go button if there's nothing to change

---

.github/workflows/ci.yml
.github/workflows/pr.yml
package-lock.json
package.json

- Include `build` in `npm test` (it was missing)
- Run `npm test` sub-commands in parallel
- Add `npm run fix` to run both `eslint --fix` and `prettier --write`
- Split up CI jobs so you know immediately which test failed, independently (lint, build, types)

chore: various fixes around CI and testing

---

components/GraphPane/reports/analyzeMaintainers.tsx
lib/Module.ts

`maintainers`  detected in the following locations, with the following priority:
1. `packument#maintainers`
2. `package@latest`
3. `packages@<version>`

fix: use packument maintainers if available, fixes #261

---

.github/workflows/pr.yml

So I figured out why GitHub was stuck on "waiting for title workflow to be reported": 
When you set a workflow as "required", it has to run on the last commit. That's why it can be fixed by changing the title right before merge (I did so in the last PR I merged)
Note: right now the "title" flow is not required because of this issue. I'll restore it after this PR is merged

chore: fix title verification

---

components/GraphPane/GraphPane.scss
components/GraphPane/GraphPane.tsx

Reapplies 
- https://github.com/npmgraph/npmgraph/pull/252
After
- #271

fix: hide empty sections in Graph tab

---

components/InfoPane/InfoPane.tsx
components/InfoPane/QueryInput.tsx
components/Inspector.scss
components/QueryLink.tsx

- Extracted unrelated style changes from https://github.com/npmgraph/npmgraph/pull/258
This prepares the tab for:
- https://github.com/npmgraph/npmgraph/pull/258
- #240 
- https://github.com/npmgraph/npmgraph/issues/277
- #276 
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="426" alt="Screenshot" src="https://github.com/user-attachments/assets/a9f92dbe-041d-44db-b987-22bd69c52406">
<td><img width="426" alt="Screenshot 16" src="https://github.com/user-attachments/assets/df1596e5-bf4a-40e8-a014-1272adcbc86e">
</table>

feat: extend instructions on Start tab

---

index.html

- Mentioned in https://github.com/npmgraph/npmgraph/pull/285
It would be nice to use https://vercel.com/docs/functions/og-image-generation to create a custom image depending on the input, but it's low priority. I'd be more interested in changing the `title` depending on the `q` instead

feat: add og:image

---

components/Intro.module.scss

I didn't really like the light mode radial gradient background colors
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>

feat: improve intro colors

---

components/ModulePane/ReleaseTimeline.tsx

Fixes this error:
https://npmgraph.js.org/?q=react-core#select=exact%3Areact-core%400.0.0
Fixed version: https://npmgraph-git-emptyreleasetimeline-broofas-projects.vercel.app/?q=react-core#select=exact%3Areact-core%400.0.0

fix: check for empty timeline in ReleaseTimeline component

---

index.html

Google wants the gtag snippet immediately after the opening HEAD token.

chore: move gtag code to HEAD

---

components/GraphDiagram/graph_util.ts
lib/ModuleCache.ts

TLDR: Shared dependencies were calculated twice for `Unpacked Size (module + dependencies):`. This PR fixes it to count once.
I was checking https://npmgraph.js.org/?q=magicast and I noticed that the `Unpacked Size (module + dependencies):` for `magicast` (root) isn't exactly accurate if you manually check the size of its dependencies.
It has a unique shared `@babel/types` dependency like this:
Before,`@babel/types` was accounted twice. Incorrectly totalling 8MB for `magicast`. This PR fixes to only account once with the new correct total being 5MB.

fix: correct downstream unpacked size calculation

---

components/GraphDiagram/graph_util.ts
components/GraphPane/colorizers/NPMSColorizer.tsx
components/Intro.module.scss
components/ModulePane/ModuleScoreBar.module.scss
components/ModulePane/ModuleScoreBar.tsx
components/ModulePane/ModuleTreeMap.tsx
components/ModulePane/ReleaseTimeline.module.scss
components/ModulePane/ReleaseTimeline.tsx
index.scss
lib/LoadActivity.ts
lib/dom.ts
lib/types.d.ts

Found myself fiddling with colors in the colorizer legends while working on #326, and ended up going all-in on the `oklch`. This is admittedly a bit of an experiment, an excuse to learn about the `oklch` colorspace.  It's [kinda weird](https://lch.oklch.com/#0.576,78.78,216.36,100), but has the advantage of providing colors with a consistent brightness when you vary the H(ue) value.
Also fixing up a few odds and ends that I turned up along the way ...
* NPMSIO colorizer legend uses CSS gradient with `scoreColor()` computed endpoints
* Use `color-mix` for color interpolation
* Tweaks to colors and styling in release timeline chart
* Wider color variation in treemap
@fregante: The tl;dr: is "a bit more color"...
Before:
After:

Colorspace

---

components/GraphPane/colorizers/BusFactorColorizer.tsx
components/GraphPane/colorizers/ModuleTypeColorizer.tsx
components/GraphPane/colorizers/OutdatedColorizer.tsx

Fixes #325.
@SuperchupuDev: If you could do some testing for this, that would be helpful (see Vercel preview build link below).  The logic I've added for detecting ESM and CJS support is almost certainly imperfect.  It just walks the `package.json#exports` field looking for `import` or `require` fields, or paths with `.mjs` or `.cjs`.  I expect it's good enough to ship, but there's no real standard for how dual-module packages should be setup.  Thus, I'm sure there will be edge cases that aren't properly detected.

fix: detect and display dual-module support in colorizer

---

components/GraphPane/colorizers/ModuleTypeColorizer.tsx

Fixes bug where `uuid@8` was detected as CJS-only, and `uuid@11` was detected as ESM-only.

fix: walk all of package.json#exports when detecting module type

---

components/GraphPane/reports/reporters/moduleReplacements.tsx
lib/ModuleCache.ts
lib/PackumentCache.ts

Fixes a bug introduced in #332 that broke package.json uploads.
tl;dr: uploaded packages don't come from a registry.

fix: packument cache bug
